### ISSUE TITLE
Feature Idea Video Playback addition? 

### ISSUE THREAD

**Issue by IkkAlpha** [ollybritton/bad-video-calculator#1]
Would this be useful in creating an extension or a bookmarklet to increase the video gradually? 

I would like to make a videplayback increased speed extension that increases speed gradually over a set period of time. For example, over 20 minutes I would like the speed to become x3, it would increase the speed +0.15 every minute, 

It would be even better if it could increase in 0.01 or even smaller increments every second over the set period of time, but if this is too complicated then the older method is better.

**Comment by ollybritton** [comment]
Hi IkkAlpha,

I don't think this can help here. This is used to calculate the rate at which the speed is increased in order to make sure the video finishes in an exact amount of time (i.e. increase a video at a rate of 0.53 at points 00:15, 00:35, 00:40, 00:58 in order to make a one minute long video take exactly 30 seconds worth of playback time).

You could probably do what you're asking yourself by forking https://github.com/igrigorik/videospeed and then adding a `setTimeout` somewhere in https://github.com/igrigorik/videospeed/blob/master/inject.js

Hope that helps!
